-- Aaride Enterprise Database Schema
-- Run this in your Supabase SQL Editor

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. Admin Users Table (For Web Admin Authentication)
CREATE TABLE IF NOT EXISTS public.admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Drivers Master Table (Driver Profile managed via Admin Portal)
CREATE TABLE IF NOT EXISTS public.drivers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE,
  password_hash TEXT NOT NULL, -- Temporary password generated by admin
  vehicle_number TEXT NOT NULL, -- e.g., TN 28 AB 3456
  vehicle_model TEXT NOT NULL,  -- e.g., Bajaj RE Auto
  license_number TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Driver Document Vault Table (Admin uploaded docs with expiry tracking)
CREATE TABLE IF NOT EXISTS public.driver_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id UUID REFERENCES public.drivers(id) ON DELETE CASCADE,
  doc_type TEXT NOT NULL, -- 'Driving License', 'RC Book', 'Vehicle Insurance', 'PAN Card', etc.
  doc_number TEXT,
  file_url TEXT NOT NULL, -- Supabase Storage Public/Signed URL
  issue_date DATE,
  expiry_date DATE, -- Crucial for alert countdowns!
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Driver Family & Welfare Table
CREATE TABLE IF NOT EXISTS public.driver_family (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id UUID REFERENCES public.drivers(id) ON DELETE CASCADE,
  member_name TEXT NOT NULL,
  relation TEXT NOT NULL, -- 'Wife', 'Son', 'Daughter', etc.
  dob DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Daily Financial Ledger (Daily Book for Income & Expenses)
CREATE TABLE IF NOT EXISTS public.driver_ledger (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id UUID REFERENCES public.drivers(id) ON DELETE CASCADE,
  entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
  income NUMERIC(10,2) NOT NULL DEFAULT 0.00, -- Total daily earnings
  expense NUMERIC(10,2) NOT NULL DEFAULT 0.00, -- Fuel/Gas, food, maintenance
  notes TEXT, -- Quick personal reminders or vehicle service notes
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_driver_documents_driver_id ON public.driver_documents(driver_id);
CREATE INDEX IF NOT EXISTS idx_driver_family_driver_id ON public.driver_family(driver_id);
CREATE INDEX IF NOT EXISTS idx_driver_ledger_driver_id ON public.driver_ledger(driver_id);
CREATE INDEX IF NOT EXISTS idx_driver_ledger_entry_date ON public.driver_ledger(entry_date);
